name: Build and deploy a container to an Azure VM with self-hosted

env:
  AZURE_VM_NAME: azure-sandbox
  REPO: test-security-workflow-scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.ACR_URL_NONPROD }}
          username: ${{ secrets.ACR_USERNAME_NONPROD }}
          password: ${{ secrets.ACR_PASSWORD_NONPROD }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_URL_NONPROD }}/${{ env.REPO }}:${{ github.sha }}
          file: Dockerfile

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Log in to Azure container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.ACR_URL_NONPROD }}
          username: ${{ secrets.ACR_USERNAME_NONPROD }}
          password: ${{ secrets.ACR_PASSWORD_NONPROD }}

      - name: Deploy code and start Docker container
        run: |
          docker pull ${{ secrets.ACR_URL_NONPROD }}/${{ env.REPO }}:${{ github.sha }}
          docker run -d -p 1001:3000 --name Retohub-web ${{ secrets.ACR_URL_NONPROD }}/${{ env.REPO }}:${{ github.sha }}

      # - name: Deploy code and start Docker container
      #   run: |
      #       docker stop ${{ env.REPO }}
      #       docker rm ${{ env.REPO }}
      #       docker pull ${{ secrets.ACR_URL_NONPROD }}/${{ env.REPO }}:${{ github.sha }}
      #       docker run -d -p 4567:3000 --name ${{ env.REPO }} ${{ secrets.ACR_URL_NONPROD }}/${{ env.REPO }}:${{ github.sha }}
